### ISSUE TITLE
automated testing

### ISSUE THREAD

**Issue by mcollina** [greguz/fastify-kubernetes#2]
I think this library would benefit having a CI system in place.
Travis, Azure, CircleCI, pick whatever you want.

I also recommend using https://www.npmjs.com/package/nock or https://github.com/thlorenz/proxyquire to mock the actual library so that you can actually run your tests without a live Kube.

(keep the previous tests, they are ok!)

**Comment by greguz** [comment]
I wasn't aware of `proxyrequire`, nice!

I've enabled Travis, and parametrized the current tests to run both under a real minikube instance or from a fake one.
